version: 0.2
phases:
    pre_build:
        commands:
            - $(aws ecr get-login --no-include-email)
            - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
            - IMAGE_URI="${REPOSITORY_URI}:${TAG}"
    build:
        commands:
            - docker build --tag "${IMAGE_URI}" -f "${CODEBUILD_SRC_DIR}/nginx-service/Dockerfile" nginx-service
    post_build:
        commands:
            - docker push "${IMAGE_URI}"
            - printf '[{"name":"%s","imageUri":"%s"}]' "${ECS_SERVICE_NAME}" "${IMAGE_URI}" > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
