---
Parameters:
  #Basic infra
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Type: String
    Default: "Test"

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this
    Type: String
    Default: "10.0.0.0/16"

  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: "10.0.0.0/24"

  PublicSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
    Type: String
    Default: "10.0.1.0/24"

  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: "10.0.2.0/24"

  PrivateSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    Default: "10.0.3.0/24"

  ECRRepoName:
    Type: String
    Default: "mogahed-ecr-repo"

  ArtifatBucketName:
    Type: String
    Default: "mogahed-bucket"

  ## Service One Prams
  ServiceOneName:
    Type: String
    Default: "nginx"
    Description: A name for the service

  ServiceOneImageUrl:
    Description: The url for the image  used to start the container
    Type: String
    Default: "nginx"

  ServiceOneContainerCpu:
    Description: cpu core speed in MHz
    Type: Number
    Default: 256

  ServiceOneContainerMem:
    Description: Amount of ram needed for the container
    Type: Number
    Default: 512
  ServiceOneAppContainerPort:
    Description: In container app port
    Type: Number
    Default: 80

  ServiceOneAppHostPort:
    Description: container mapped port in the host
    Type: Number
    Default: 80

  ServiceOneDesiredCount:
    Type: Number
    Default: 1
    Description: How many copies of the service task to run

  ServiceOneVarPath:
    Type: String
    Default: "/"
    Description: Path for service route and healthcheck

  #Pipeline
  ServiceOnePipelineName:
    Description: Name of the pipeline
    Type: String
    Default: test-nginx

  ServiceOneBranchName:
    Description: GitHub branch name
    Type: String
    Default: main

  ServiceOneRepositoryName:
    Description: GitHub repository name
    Type: String
    Default: cicd-demo

  ServiceOneGithubToken:
    Type: String
    NoEcho: true

  ServiceOneGithubOwner:
    Type: String
    Default: AhmedMojahed

  ServiceOneBuildSpecPath:
    Type: String
    Default: nginx/buildspec.yml

  ServiceOneListenerPriority:
    Type: Number
    Default: 1

  ## Service Two Prams
  ServiceTwoName:
    Type: String
    Default: "httpd"
    Description: A name for the service

  ServiceTwoImageUrl:
    Description: The url for the image  used to start the container
    Type: String
    Default: "httpd"

  ServiceTwoContainerCpu:
    Description: cpu core speed in MHz
    Type: Number
    Default: 256

  ServiceTwoContainerMem:
    Description: Amount of ram needed for the container
    Type: Number
    Default: 512
  ServiceTwoAppContainerPort:
    Description: In container app port
    Type: Number
    Default: 80

  ServiceTwoAppHostPort:
    Description: container mapped port in the host
    Type: Number
    Default: 80

  ServiceTwoDesiredCount:
    Type: Number
    Default: 1
    Description: How many copies of the service task to run

  ServiceTwoVarPath:
    Type: String
    Default: "/"
    Description: Path for service route and healthcheck

  #Pipeline
  ServiceTwoPipelineName:
    Description: Name of the pipeline
    Type: String
    Default: test-httpd

  ServiceTwoBranchName:
    Description: GitHub branch name
    Type: String
    Default: main

  ServiceTwoRepositoryName:
    Description: GitHub repository name
    Type: String
    Default: cicd-demo

  ServiceTwoGithubToken:
    Type: String
    NoEcho: true

  ServiceTwoGithubOwner:
    Type: String
    Default: AhmedMojahed

  ServiceTwoBuildSpecPath:
    Type: String
    Default: httpd/buildspec.yml

  ServiceTwoListenerPriority:
    Type: Number
    Default: 2

Resources:
  BasicInfra:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://mogahed-halan-test-templates.s3.us-east-2.amazonaws.com/NetworkBasicInfra.yml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
        ECRRepoName: !Ref ECRRepoName
        ArtifatBucketName: !Ref ArtifatBucketName

  # Services ## copy this resource > create new prams > rename new resource and prams in it
  ServiceOneStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://mogahed-halan-test-templates.s3.us-east-2.amazonaws.com/ServiceWithPipeline.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ServiceName: !Ref ServiceOneName
        ImageUrl: !Ref ServiceOneImageUrl
        ContainerCpu: !Ref ServiceOneContainerCpu
        ContainerMem: !Ref ServiceOneContainerMem
        AppContainerPort: !Ref ServiceOneAppContainerPort
        AppHostPort: !Ref ServiceOneAppHostPort
        DesiredCount: !Ref ServiceOneDesiredCount
        VarPath: !Ref ServiceOneVarPath
        PipelineName: !Ref ServiceOnePipelineName
        BranchName: !Ref ServiceOneBranchName
        RepositoryName: !Ref ServiceOneRepositoryName
        GithubToken: !Ref ServiceOneGithubToken
        GithubOwner: !Ref ServiceOneGithubOwner
        BuildSpecPath: !Ref ServiceOneBuildSpecPath
        ListenerPriority: !Ref ServiceOneListenerPriority
        ECRRepoName: !GetAtt BasicInfra.Outputs.EcrRepo
        ArtifatBucketName: !GetAtt BasicInfra.Outputs.Artifact

  ServiceTwoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://mogahed-halan-test-templates.s3.us-east-2.amazonaws.com/ServiceWithPipeline.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ServiceName: !Ref ServiceTwoName
        ImageUrl: !Ref ServiceTwoImageUrl
        ContainerCpu: !Ref ServiceTwoContainerCpu
        ContainerMem: !Ref ServiceTwoContainerMem
        AppContainerPort: !Ref ServiceTwoAppContainerPort
        AppHostPort: !Ref ServiceTwoAppHostPort
        DesiredCount: !Ref ServiceTwoDesiredCount
        VarPath: !Ref ServiceTwoVarPath
        PipelineName: !Ref ServiceTwoPipelineName
        BranchName: !Ref ServiceTwoBranchName
        RepositoryName: !Ref ServiceTwoRepositoryName
        GithubToken: !Ref ServiceTwoGithubToken
        GithubOwner: !Ref ServiceTwoGithubOwner
        BuildSpecPath: !Ref ServiceTwoBuildSpecPath
        ListenerPriority: !Ref ServiceTwoListenerPriority
        ECRRepoName: !GetAtt BasicInfra.Outputs.EcrRepo
        ArtifatBucketName: !GetAtt BasicInfra.Outputs.Artifact
